### ISSUE TITLE
HMR triggered but no update on client side

### ISSUE THREAD

**Issue by HubnesterRising** [sync/plugin-lit-refresh#1]
Hello,

What type of configuration/import/etc do you use for the styles property to have the styles update client side?

Currently, with a clean install of the `lit-ts` `vite` template, this plugin configuration, and loading of the css via import 
```ts
  import componentStyles from './my-element.css'
  static styles = [
    css`${unsafeCSS(componentStyles)}`
  ]
```
the HMR is triggered but no update is seen client side

currently using 
```json
{
   "vite": "^2.8.4",
   "lit": "^2.2.0"
}
```
also tried using `"vite": "^2.3.0"`, from ~9 month ago when you published the plugin. That seemed to make no difference.

**Comment by sync** [comment]
It was in combination with Tailwind, this was pre Vite 2 I think it's been a while I stopped using Lit (back to doing React because my work / priorities changed work) Feel free to fork it and maintain your own version. This was just an experiment, it worked at one point.

**Comment by HubnesterRising** [comment]
Ah yes. I forgot to mention I had Tailwind installed, configured, and generating correctly sans HMR.
Thank you!
